version: '3.8'
name: dep-checker-infra
services:
  redis:
    image: redis:alpine
    container_name: redis
    environment:
      REDIS_ARGS: '--requirepass password'
    ports:
      - '6379:6379'
    networks:
      - app-network

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: dep-checker-app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    ports:
      - '8000:8000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
